// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {type: "autogenerated", dirName: '.'}
  ],
  whitepaper: [
  {
    type: 'category',
    label: 'Whitepaper',
    collapsed: false,
    items: [
      {
        type: 'autogenerated',
        dirName: 'whitepaper'
      }
    ]
  }],
  nodes: [
    {
      type: 'category',
      label: 'Nodes & Validators',
      items: [
        {
          type: 'autogenerated',
          dirName: 'nodes'
        }
      ]
    },
  ],
  "tech-documentation": [{
    type: 'category',
    label: 'Technical documentation',
    items: [
      {
        type: 'autogenerated',
        dirName: 'tech-documentation'
      }
    ]
  }],
  faq: [{
    type: 'doc',
    id: 'faq/faq',
    label: 'FAQ'
  }]
}

module.exports = sidebars
