// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebar: [
    {
      type: 'category',
      label: 'Whitepaper',
      items: [
        {
          type: 'autogenerated',
          dirName: 'whitepaper'
        }
      ]
    },
    'qna/qna'
  ]
}

module.exports = sidebars
