// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  okp4Sidebar: [
    "index",
      ],

  whitepaperSidebar: [
    {
      type: 'category',
      label: 'Whitepaper',
      items: [
        {
          type: 'autogenerated',
          dirName: 'whitepaper'
        }
      ]
    },
    {
      type: 'doc',
      id: 'faq/faq',
      label: 'FAQ'
    }
  ],
  nodesSidebar: [
    {
      type: 'category',
      label: 'Nodes & Validators',
      items: [
        {
          type: 'autogenerated',
          dirName: 'nodes'
        }
      ]
    }
  ]
}

module.exports = sidebars
